### ISSUE TITLE
Invalid Push Token causes several proceeding pushes to fail

### ISSUE THREAD

**Issue by kurabi** [notnoop/java-apns#104]
Problem:
Invalid Push Token causes several proceeding pushes to not be sent to devices even though the java-apns library says they have been pushed successfully

Test Scenario:
-3 Phones registered for push notification
-All 3 phones are able to receive push notifications
-Then I uninstall the app from phone #1
-Server attempts push a payload to all 3 tokens(phones) that it has registered
-java-apns pushes the first token (invalid one, phone with uninstalled app), recognizes its no longer valid, calls the "messageSendFailed" delegate as expected.  Then states that the remaining 2 device tokens were pushed successfully however the remaining 2 devices did NOT receive the push notification.

Hacky Fix:
-If I put a Thread.sleep(2000) in the "messageSendFailed", the proceeding 2 pushes get sent to the devices correctly.

Also I noticed that if you execute any operation in the "messageSendFailed" that things work. If you do nothing, then you see this issue. 

Definitely a timing issue.

**Comment by amolpotnis** [comment]
Is this issue fixed in 1.0.0.Beta6? I am confused. I am still facing the same issue with 1.0.0.Beta6. Please confirm.
