### ISSUE TITLE
Deadlock issue in ApnsConnectionImpl

### ISSUE THREAD

**Issue by snoopdave** [notnoop/java-apns#134]
I'm starting to investigate this now, but perhaps somebody has some clues for me?

The following deadlock was detected by New Relic in the java-apns code:

Error message
Deadlock: Deadlocked thread: Thread-152

Stack trace Thread-151
      sun.security.ssl.SSLSocketImpl.getConnectionState (SSLSocketImpl.java:649)
                sun.security.ssl.SSLSocketImpl.isClosed (SSLSocketImpl.java:1446)
                          java.net.Socket.getTcpNoDelay (Socket.java:953)
       sun.security.ssl.BaseSSLSocketImpl.getTcpNoDelay (BaseSSLSocketImpl.java:345)
     sun.security.ssl.SSLSocketImpl.writeRecordInternal (SSLSocketImpl.java:819)
             sun.security.ssl.SSLSocketImpl.writeRecord (SSLSocketImpl.java:801)
                 sun.security.ssl.AppOutputStream.write (AppOutputStream.java:122)
                             java.io.OutputStream.write (OutputStream.java:75)
…m.notnoop.apns.internal.ApnsConnectionImpl.sendMessage (ApnsConnectionImpl.java:240)
…m.notnoop.apns.internal.ApnsConnectionImpl.drainBuffer (ApnsConnectionImpl.java:273)
com.notnoop.apns.internal.ApnsConnectionImpl.access$600 (ApnsConnectionImpl.java:56)
…apns.internal.ApnsConnectionImpl$1MonitoringThread.run (ApnsConnectionImpl.java:163)

Stack trace Thread-152
                                   sun.misc.Unsafe.park (Native Method)
            java.util.concurrent.locks.LockSupport.park (LockSupport.java:186)
…locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt (AbstractQueuedSynchronizer.java:834)
…current.locks.AbstractQueuedSynchronizer.acquireQueued (AbstractQueuedSynchronizer.java:867)
…il.concurrent.locks.AbstractQueuedSynchronizer.acquire (AbstractQueuedSynchronizer.java:1197)
…a.util.concurrent.locks.ReentrantLock$NonfairSync.lock (ReentrantLock.java:214)
          java.util.concurrent.locks.ReentrantLock.lock (ReentrantLock.java:290)
             sun.security.ssl.SSLSocketImpl.writeRecord (SSLSocketImpl.java:799)
             sun.security.ssl.SSLSocketImpl.writeRecord (SSLSocketImpl.java:672)
               sun.security.ssl.SSLSocketImpl.sendAlert (SSLSocketImpl.java:2007)
                 sun.security.ssl.SSLSocketImpl.warning (SSLSocketImpl.java:1834)
           sun.security.ssl.SSLSocketImpl.closeInternal (SSLSocketImpl.java:1602)
               sun.security.ssl.SSLSocketImpl.recvAlert (SSLSocketImpl.java:1943)
              sun.security.ssl.SSLSocketImpl.readRecord (SSLSocketImpl.java:1077)
          sun.security.ssl.SSLSocketImpl.readDataRecord (SSLSocketImpl.java:884)
                   sun.security.ssl.AppInputStream.read (AppInputStream.java:102)
                               java.io.InputStream.read (InputStream.java:101)
…apns.internal.ApnsConnectionImpl$1MonitoringThread.run (ApnsConnectionImpl.java:114)

**Comment by santosh-1987** [comment]
@JMacLulich : Still I am facing the same issue in Servers.

Can u please list out the steps , for disabling monitoring thread and setup pooled connections.
