### ISSUE TITLE
Callback using EnhancedApnsNotification?

### ISSUE THREAD

**Issue by confile** [notnoop/java-apns#154]
You wrote that you get feedback when using EnhancedApnsNotification. How? Is there a callback function?

**Comment by asafdavid** [comment]
Hi,
Could someone explain to me: when do I get push error in ApnsDelegate and when via the Feedback server?

**Comment by matzew** [comment]
feedback service gives you info on apps (their tokens) that got uninstalled (or push disabled):
https://github.com/notnoop/java-apns/blob/master/src/main/java/com/notnoop/apns/ApnsService.java#L155-L160

You explicitly have to call the service to receive the info. While ApnsDelegate is for actual errors when sending a push to the server.
