### ISSUE TITLE
Use the "Binary Interface and Notification Format"

### ISSUE THREAD

**Issue by jcesarmobile** [notnoop/java-apns#176]
From the apple doc (https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/LegacyFormat.html#//apple_ref/doc/uid/TP40008194-CH105-SW1):

New development should use the modern format to connect to APNs, as described in “The Binary Interface and Notification Format.” (https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW4)

So the Simple Notification Format and Enhanced Notification Format are legacy now and we should use the new "Binary Interface and Notification Format" instead

**Comment by KimRagnaMertens** [comment]
When are you releasing the new format? I look urgently forward to it, otherwise my client may ask me to implement it as a fork of your repository. which revision can i fork from? since master fork is red according to ci...
