### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by simsekanil** [notnoop/java-apns#227]
I get this error everytime I try to send a push notification, but not when opening the connection. I use app engine backend servers and use this code to initiate the service
InputStream is = getClass().getClassLoader().getResourceAsStream("/Certificate.p12");
		
		
		String password = "password" ;
		
		service = APNS.newService()
				.withCert(is, password)
				.withSandboxDestination()
				.withNoErrorDetection()
				.build();
                String payload = APNS.newPayload().alertTitle("Hello World").build() ;
		service.start(); 
		service.push("some token", payload);
Is there something obvious that I am missing ?

**Comment by matzew** [comment]
@simsekanil Just curious, does
```
ApnsService service =
    APNS.newService()
    .withCert("/path/to/certificate.p12", "MyCertPassword")
    .withSandboxDestination()
    .build();
``` 

work ?

**Comment by simsekanil** [comment]
Hey I found the error it was because of maven filtering, I turned of filtering for p12 files and it worked. By the way your code did not work because of the app engine sandbox file system, it throws an exception indicating  that access denied,
