### ISSUE TITLE
Still can sent Push Notifications with invalid tokenId

### ISSUE THREAD

**Issue by JavaHelper** [notnoop/java-apns#260]
I see APNS java code doesn't work properly. I am using wrong device token still it saying success. 
``` Message sent successfullyMessage(Id=1; Token=8847579D9C5588ABD43767DBC2130B1454CA289A; Payload={"aps":{"badge":45,"alert":"Testing APNS from India !!","sound":"default"}}),Resent :false```

I am using withSandboxDestination()

**Comment by matzew** [comment]
well - it does not say: "successfully sent to device" - it means successfully delivered to APNS ;-)

There is a delegate interface, which gives some more info about state of the token

**Comment by JavaHelper** [comment]
How we could come to know its sent successfully to device ? I am using following code, Please please help me and don't close ticket.

```
ApnsService pushService = APNS.newService()
				.withCert("test.p12", "pass")
				.withSandboxDestination()
				.withDelegate(new ApnsDelegate() {
					
					public void notificationsResent(int resendCount) {
						System.out.println(resendCount);
					}
					public void messageSent(ApnsNotification message, boolean resent) {
						System.out.println("Message sent.  Payload: " + message);
					}

					public void messageSendFailed(ApnsNotification message, Throwable e) {
						System.out.println("Message send failed.  Message: " + message.toString() + " token " + message.getDeviceToken().toString() + " " + message.getPayload().toString());
					}
					public void connectionClosed(DeliveryError e, int messageIdentifier) {
						System.out.println("Connection closed.  Message: " + e.toString());
					}

					public void cacheLengthExceeded(int newCacheLength) {
						System.out.println(newCacheLength);
					}
				}).build();
```

**Comment by matzew** [comment]
There is no way to tell that it was delivered to a device. This handles JUST the connection to APNs itself.

Imagine the case, a phone being offline for 12 hours, due to a long flight. Once the phone starts again after arriving, the push goes through the device... in that case should your callback sit there for 12 hours and wait ? :)

**Comment by JavaHelper** [comment]
My question is if I am using invalid device token (such token which doesn't exists), how can I get invalid token / failed message? I am using below:
String token = "9c5588ab f50b6654 d43767db cc19ba86 c2130b14";

**Comment by matzew** [comment]
I think the INVALID_TOKEN is used when a SANDBOX token is send to the PRODUCTION server, and vice versa. Not sure if some made up tokens are marked as 'invalid' from APNs

**Comment by KimRagnaMertens** [comment]
In ApnsDelegate#messageSentFailed you can examine the exception (mostly it will be ApnsDeliveryErrorException or NetworkIOException or InvalidSSLConfig ) and the device token and payload is stored in the message. Please note: for invalid device token call apple feedback service!

@Override
	public void messageSendFailed(ApnsNotification message, Throwable e) {
		this.loggingService.logMessageSendFailed(e, ApplePushService.SERVICE_NAME, message.getIdentifier(),
				Utilities.encodeHex(message.getDeviceToken()), new String(message.getPayload()));
	}

**Comment by matzew** [comment]
here is what we use:

https://github.com/aerogear/aerogear-unifiedpush-server/blob/fbd8bbfaa0b5b14cfbbf62f9a9622084db0fdd34/push/sender/src/main/java/org/jboss/aerogear/unifiedpush/message/sender/APNsPushNotificationSender.java#L228-L238

Regarding the APNS Feedback Service, it's just for inactive tokens (e.g. where push was disabled or the app was removed from the phone)

**Comment by JavaHelper** [comment]
Every time following method is getting called (please refer my mail above) although I give empty token like String token="";, I wonder why its not messageSendFailed or connectionClosed?

I am really seeing weird behaviour, Please try same and help / guide me 

 public void messageSent(ApnsNotification message, boolean resent) {
                        System.out.println("Message sent.  Payload: " + message);
                    }
