### ISSUE TITLE
How did I know to push a message failed, through ApnsService.push(deviceToken, payload)

### ISSUE THREAD

**Issue by freecs** [notnoop/java-apns#292]
use the API     ApnsService.push(deviceToken, payload) to push a message
how did I know push failed?

**Comment by LostKe** [comment]
when build ApnsService you can 
ApnsService service=APNS.newService().withDelegate(new ApnsDelegate())...
when push failed will callback ApnsDelegate.messageSendFailed() method

**Comment by freecs** [comment]
@LostKe  Got it. 
Thanks.
