### ISSUE TITLE
Invalid token will influence the senquential good tokens in one connection

### ISSUE THREAD

**Issue by LilyBlooper** [notnoop/java-apns#312]
Hi, I think this problem is typical .
I have a ios app . which creat a new token each time I reinstalled.
For example , **I have 2 tokens : one is old and invalid (A )and one is new and valid.(B)**
I create a  APNSservice and push these 2 tokens senquentially . (A then B)
the result is weird . 
Both were pushed successfully . 
I use this code to check if it it sucessful , is it right?

``` java
        ApnsNotification notification = service.push(eachDeviceId, payload);
        if (notification.getDeviceToken().length != 0) {
            System.out.println("Success!"+notification.getDeviceToken());
        }
```

Then , **the first invalid token will influence the next valid token.** 
Ideally I should receive one notification , however it is not . Sometime can ,other are not . and there is 
no pattern . **It just randomly works!!!**

**On the contrary , if I push these two tokens individually , the result is as expected .** 
( If I just push invalid token A , I never receive notifications,
If I just push valid token B , I always receive one notification . This is right!)

So， personally I think any invalid tokens in the to-be-pushed token list will disturb the following token's normal push . 

Please check and reply to me asap ! 
I think this is a common issue,

**Comment by JellyB** [comment]
Does it solved?

**Comment by LilyBlooper** [comment]
Noop . Try to remove invalid token periodically, and make the batch size small .
Or try another library : Pushy, however it it based on HTTP/2 .
