### ISSUE TITLE
sound not emmited

### ISSUE THREAD

**Issue by mdkouki** [notnoop/java-apns#44]
Despite using the 'default' sound no sound is emmited:

PayloadBuilder apnsPayLoad = APNS.newPayload();
apnsPayLoad.alertBody(textMessage);
apnsPayLoad.sound("default");

thanks for your Help,

**Comment by dangvhuy** [comment]
Dear all,

I am facing on the same problem.

**the problem was in the registration params**
Would you please tell me what was wrong?
Thank you.
