### ISSUE TITLE
MDM Support

### ISSUE THREAD

**Issue by slowbrewedmacchiato** [notnoop/java-apns#88]
Hi @notnoop,

it seems the library supports MDM. I build my mdm "wake up" push notification using a SimpleApnsNotification object. The Built payload looks like the following:

BUILT PAYLOAD: {"aps":{},"mdm":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}

However, I believe according to the documentation an MDM payload should only contain the following: {"mdm":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}.

Is there a specific class to achieve the above? I looked through the Javadocs but couldn't come up with anything.

Regards.

**Comment by pedy711** [comment]
@karldmoore @mayuranwso2mobile I can send `APNS.newPayload().mdm("PushMagic").build();` with no problem and I receive "idle" msg from the device, but I don't know how to build a command like "DeviceLock". Could you please provide me with some example?

**Comment by pedy711** [comment]
Thanks for your prompt reply. I am already aware of how the command should look like in plist. In fact, I have already created it as below. But my problem is how to send this obj via notnoop java-apns library. It seems it is only possible to send mdm "Wakeup" call to the device and get back "Idle" msg from the device using this library.

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList- 
    1.0.dtd">
    <plist version="1.0">
    <dict>
	    <key>Command</key>
	    <dict>
		    <key>RequestType</key>
		    <string>DeviceLock</string>
	    </dict>
	    <key>CommandUUID</key>
	    <string>dd889c2b-0fc0-4846-87b9-f77a07d98a2a</string>
    </dict>
    </plist>

**Comment by karldmoore** [comment]
You wouldn't send those commands via the library.  This library asks the device to phone home back to the MDM server.  Once it's phoned home, you can then send it the next command to process e.g. DeviceLock.  It will response to the server and then you send the next command.  Until it's processed all of the queued commands.

You always queue the commands for the device and then ask it to call you because there is something to process.  That's the protocol.

**Comment by pedy711** [comment]
@karldmoore thanks a lot. I made it work with a simple plist response without using the library.
